### ISSUE TITLE
Don’t use fixed size string array

### ISSUE THREAD

**Issue by TravorLZH** [ParadoxZero/stmp#9]
https://github.com/ParadoxZero/stmp/blob/d09d15d778e9d0b581ee8cb212fe8580e8de7603/stmp/src/stmp_process.c#L94

To me, that takes too much memory, try to use replace those fixed size stuff with some **malloc**. You don’t want a blank line to take 300 bytes.

**Comment by ParadoxZero** [comment]
Not an issue, hardly a dent to available memory.
